name: Update CV
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 12 1 * *'

jobs:
  notebooks:
    name: "Update CV"
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update CV
        run: |
          rm James__CV.pdf
          git clone https://github.com/James11222/James_CV.git
          cp James_CV/resume.pdf James__CV.pdf
          rm -rf James_CV/

      - run: git pull

      - name: Committing changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update CV
